language: java
 
# Clear the learnpad JARs to avoid recaching every time
script: bash build --debug --clean-jar

# We need to remove sudo for caching on Travis
# http://docs.travis-ci.com/user/caching/
sudo: false

addons:
    apt:
        packages:
            - curl
            - gcc
            - make
            - maven
            - nodejs
            - openjdk-7-jdk
            - openjdk-7-jre


cache:
    directories:
        - $HOME/.m2

after_success:
    - bash <(curl -s https://codecov.io/bash)
